### ISSUE TITLE
Add Managed Upgrade Operator to OperatorHub

### ISSUE THREAD

**Issue by simonkrenger** [openshift/managed-upgrade-operator#329]
Hello team,

The Managed Upgrade Operator can also be used by Red Hats customers to partially automate the upgrades for their own OpenShift clusters. Customers must be aware that this is not a supported Operator, but this has so far never been a problem.

However, customers have asked about having the Managed Upgrade Operator available in the OpenShift OperatorHub so it can be installed and managed via the OperatorHub.

Likely it would make sense to add the Operator to the "Community" marketplace in OperatorHub, as Red Hat does not officially support this Operator.

What do you think, would that be a possible enhancement?

Thanks.

**Comment by dofinn** [comment]
Hi @simonkrenger , 

Thanks for opening this issue and exploring this topic with us. At the moment there are no plans to make the managed-upgrade-operator apart of Operator Hub as current development efforts are highly coupled with the our managed services goals. 

Thanks.
